//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astronautai
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player(int id, int x, int y)
        {
            Id = id;
            X = x;
            Y = y;
        }

        public int Id { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string Input { get; set; }
    }
}
